<?php

namespace common\widgets;

use yii\base\Widget;
use yii\helpers\Html;

class BgWidget extends Widget
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        obs_start();
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $output = ob_get_clean();
        return Html::tag('div', $output, [
                'style' => 'background-color: blue'
            ]);
    }

}